version: "3.9"
services:
  api:
    image: "bytely_api:latest"
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - BYTELY_PORT=8080
      - BYTELY_DATABASE_CONNECTION_STR=postgresql://postgres:postgres@db:5432/bytely?sslmode=disable
      - BYTELY_LOG_LEVEL=debug
    links:
      - "db:postgres"

  client:
    image: "bytely_client:latest"
    ports:
      - "80:80"
    depends_on:
      - api
    environment:
      - BYTELY_PORT=80
      - BYTELY_LOG_LEVEL=debug
      - BYTELY_GRPC_SERVER_ADDR=api:8080
      - BYTELY_DOMAIN=localhost

  db:
    image: "postgres:latest"
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=bytely
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  test_db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=bytely
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  db:
    driver: local
